blogs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.models import User
#from rest_framework import routers, serializers, viewsets

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categories/', include('categories.urls')),
    path('users/',include('users.urls')),
    path('post/',include('post.urls')),
    #url(r'^api-auth/', include('rest_framework.urls')),



    #path('api/',include('users.rest_url')),
    #path('api/',include('post.rest_url')),
    
]

post/urls.py
from django.urls import path
from post import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'post'

urlpatterns = [
	
	path('add_post/', views.AddPost.as_view(), name='add_post'),
	path('view_post/', views.ViewPost.as_view(), name='view_post'),
	path('like_post/<int:post_id>', views.LikePost.as_view(), name='like_post'),
	path('comment_post/<int:post_id>', views.CommentPost.as_view(), name='comment_post'),
	
	


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views
from django.views.generic import TemplateView, View

app_name = 'users'

urlpatterns = [
	
	path('', views.Index.as_view(), name='index'),
	path('login/', views.LoginView.as_view(), name='login_view'),
	path('register/',views.Register.as_view(), name='register'),
	path('logout/', views.LogoutView.as_view(), name='logout_view'),
	

]

post/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from categories.models import Category, SubCategory
from django.forms import ModelForm

# Create your models here.
class UserPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    sub_category = models.ForeignKey(SubCategory, on_delete=models.CASCADE, blank=True,null=True)
    image = models.ImageField(upload_to = "images") 
    title = models.CharField(max_length=200)
    description = models.TextField()
    location = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self): 
        return self.title 

class PostLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(UserPost, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self): 
        return self.post

class PostComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(UserPost, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    text = models.TextField()

post/forms.py
from django import forms
from django.forms import ModelForm
from post.models import UserPost

# class PostForm(forms.Form):
            
#     image = forms.ImageField(label='Image ')
#     title = forms.CharField(label='Title ', max_length=100)
#     location = forms.CharField(label='Location ', max_length=100)
#     description = forms.CharField(label='Description ',widget=forms.Textarea)

class PostModelForm(ModelForm):

    class Meta:
        model = UserPost
        fields = ['image','title','location','description']

    field_order = ['image','category','location','description','title']
    

post/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from categories.models import Category, SubCategory
from . models import UserPost, PostLike, PostComment
from django.views import View
import datetime
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from PIL import Image
from django.contrib.auth.decorators import login_required
from . forms import PostModelForm
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import datetime, timedelta
from django.utils.timesince import timesince
from collections import defaultdict
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.models import Count
from .serializers import PostSerializer


class AddPost(View):
    
    def get_alertnum(user):
        return Alert.objects.filter(read=False, for_user=user).count()

    #@login_required
    def get(self, request):

        form = PostModelForm()
        category_objs = Category.objects.all()
        context = {'category_objs':category_objs, 'form' : form}
        return render(request, 'post/add_post.html', context)
    
    
    #@login_required(login_url='/accounts/login/')
    def post(self, request):
        #import pdb;pdb.set_trace()
        form = PostModelForm(request.POST, request.FILES)
        if form.is_valid():
            # my_image = new.cleaned_data['image']
            category = request.POST.get('category_id')
            category_obj = Category.objects.get(id=category)
            # title = new.cleaned_data['title']
            # description = new.cleaned_data['description']
            # location = new.cleaned_data['location']
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.category = category_obj
            new_post.save()
            return redirect('users:index')
        
        category_objs = Category.objects.all()
        context = {'category_objs':category_objs, 'form' : form}
        return render(request, 'post/add_post.html', context)
        
            #new_post = UserPost.objects.create(user=request.user, category = category_obj, image=my_image, title=title,description=description, location=location)
        
         

       
class ViewPost(View):
    def get(self, request):
        if request.user.is_authenticated:
            post_objs = UserPost.objects.all().annotate(likes_count=Count('postlike')).prefetch_related('postcomment_set').order_by('-created')
            #import pdb;pdb.set_trace()
            #comment_objs = PostComment.objects.select_related('post').all().order_by()
            #now = datetime.now()
            #post_objs.postlike_set.all().count()
            # context = defaultdict(list)
            # for obj in post_objs:
            #     difference = now - post_objs.created
            #     context['since_time'].append(difference)

            

            # since_time =  '%(time)s ago' % {'time': timesince(value).split(', ')[0]}
            context = {'post_objs':post_objs}
            return render(request, 'post/view_post.html', context)
        else:
            return redirect('post:view_post')

class LikePost(View):
    def get(self, request,*args,**kwargs):
        #import pdb;pdb.set_trace()
        if request.user.is_authenticated:
            #import pdb;pdb.set_trace()
            
            #obj = PostLike.objects.filter(user=request.user)
            #if obj.user_id == True:
            #obj.delete()
            user = request.user
            p_id = kwargs['post_id']
            post = UserPost.objects.get(id=p_id)
            like = PostLike.objects.create(user=user,post=post)
            
        return redirect('post:view_post')
      
class CommentPost(View):

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(CommentPost, self).dispatch(request, *args, **kwargs)

    def get(self,request, *args, **kwargs):
        if request.user.is_authenticated:
            p_id = kwargs['post_id']
            obj = UserPost.objects.get(id=p_id)
            return render(request, 'post/comment_post.html', {'obj':obj})
    
    def post(self, request, *args,**kwargs):
        #import pdb;pdb.set_trace()
        if request.user.is_authenticated:
            user = request.user
            p_id = kwargs['post_id']
            post = UserPost.objects.get(id=p_id)
            text = request.POST.get('comment')
            comment = PostComment.objects.create(user=user, post=post, text=text)
            
        return redirect('post:view_post')
    
    

post/templates/post/add_post.html
{% extends 'users/index.html'%}
{% block body_content %}

{% if request.user.is_authenticated %}

<h2>Add Post</h2>
<h3>Select Category</h3>



<form href=" {%url 'post:add_post'%}" method='POST' enctype="multipart/form-data">
  {% csrf_token %}
  
  <select  name="category_id" autofocus="" required="">
  		
  {% for obj in category_objs %}
        <option value={{obj.id}}>{{obj.name}}</option>
  {% endfor %}

   </select>
   <br><br>

    <p>  {{form.title.label}} {{form.title}}  {{form.title.errors}}</p>
    <p>  {{form.image.label}} {{form.image}}</p>
    <p>  {{form.location.label}}  {{form.location}}</p>
    <p>  {{form.description.label}}  {{form.description}}</p>
    <p>  <input type="submit"></p>

  {% comment %}
  {% if form.errors %}
    <div class="alert alert-error">
      <h4>Please fix the following errors</h4>
      <ul>
        {% for field in form %}
        {{field}}
          {% if field.errors %}
            {% for error in field.errors %}
              <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
          {% endif %}
        {% endfor %}
      </ul>
      {% if form.non_field_errors %}
        {{ form.non_field_errors }}
      {% endif %}
    </div>
  {% endif %}
{% endcomment %}

</form>

<hr>


{%else%}

<a href="{% url 'users:index' %}">Index</a>
{% endif %}

{% endblock %}

post/templates/post/comment_post.html
{% load static %}
{% load custom_tags %}

<h2>Post</h2>
<br><br>
		{{obj.title}}<br>
		{{obj.created}}<br>
		{% days obj as time_day %}
		{%if time_day == 0 %}
		Posted Today
		{%else%} 
		Posted {{time_day}} days ago
		{% endif %}<br>
		{{obj.location}}<br>
		{{obj.user}}<br>
		{{obj.category}}<br>
		{{obj.description}}<br>
		<img src="{{ obj.image.url }}"/><br><br>
		<form href="{% url 'post:comment_post' obj.id%}" method="POST">
		{% csrf_token %}
			<label for='comment'>Comment</label>
			<input type="text" name="comment">
			<input type="submit">
		</form>

post/templates/post/view_post.html
{% load static %}
{% load custom_tags %}


<h1>Post</h1>

	{% for objs  in post_objs%}
	<br><br>
		
		{{objs.title}}<br>
		{{objs.created}}<br>
		{% days objs as time_day %}
		{%if time_day == 0 %}
		Posted Today
		{%else%} 
		Posted {{time_day}} days ago
		{% endif %}<br>
		{{objs.location}}<br>
		{{objs.user}}<br>
		{{objs.category}}<br>
		{{objs.description}}<br>
		<img src="{{ objs.image.url }}"/><br><br>

		{{objs.likes_count}}
		<a href="{% url 'post:like_post' objs.id%}">Like</a>
		{{objs.postcomment_set.all.count}}
		<a href="{% url 'post:comment_post' objs.id %}">Comment</a>
		
		

		<hr>
	
	{% endfor %}