blogs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.models import User
#from rest_framework import routers, serializers, viewsets

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categories/', include('categories.urls')),
    path('users/',include('users.urls')),
    path('post/',include('post.urls')),
    #url(r'^api-auth/', include('rest_framework.urls')),



    #path('api/',include('users.rest_url')),
    #path('api/',include('post.rest_url')),
    
]

categories/urls.py
from django.urls import path
from . import views

app_name = 'categories'

urlpatterns = [
	
	path('add_category/', views.AddCategory.as_view(), name='add_category'),
	path('show_category/', views.ShowCategory.as_view(), name='show_category'),
	path('add_sub_category', views.AddSubCategory.as_view(), name='add_sub_category'),
	


]

post/urls.py
from django.urls import path
from post import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'post'

urlpatterns = [
	
	path('add_post/', views.AddPost.as_view(), name='add_post'),
	path('view_post/', views.ViewPost.as_view(), name='view_post'),
	path('like_post/<int:post_id>', views.LikePost.as_view(), name='like_post'),
	path('comment_post/<int:post_id>', views.CommentPost.as_view(), name='comment_post'),
	
	


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views
from django.views.generic import TemplateView, View

app_name = 'users'

urlpatterns = [
	
	path('', views.Index.as_view(), name='index'),
	path('login/', views.LoginView.as_view(), name='login_view'),
	path('register/',views.Register.as_view(), name='register'),
	path('logout/', views.LogoutView.as_view(), name='logout_view'),
	

]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.views.generic import TemplateView, View
from categories.models import Category, SubCategory

# Create your views here.
class Index(View):
    
    def get(self, request):
        category_objs = Category.objects.all()
        context = {'category_objs':category_objs}
        return render(request, 'users/index.html',context)

class LoginView(View):

	def get(self, request):
		return render(request, 'users/login_view.html',{})

	def post(self, request):
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(username=username, password=password)
		if user is not None:
			login(request,user)
			return redirect('users:index')
		else:
			return redirect('users:index')

class LogoutView(View):
	def get(self,request):
		logout(request)
		return redirect('users:index')
	
		
class Register(View):
		
		def get(self, request):
			return render(request, 'users/register.html',{})	

		def post(self,request):
			fname = request.POST.get('fname')
			lname = request.POST.get('lname')
			username = request.POST.get('username')
			password = request.POST.get('password')	
			email = request.POST.get('email')
			user = User.objects.create_user(username=username,first_name=fname,last_name=lname,email=email)
			user.set_password(password)
			user.save()
			return redirect('users:index')

users/templates/users/about.html
<h1>About Us</h1>

users/templates/users/heading.html
<h1>Welcome To Blog App</h1>

users/templates/users/index.html
{% load custom_tags %}

<!DOCTYPE html>
<html>
   
   <head>
      <title>Bootstrap 101 Template</title>
      <meta name = "viewport" content = "width = device-width, initial-scale = 1.0">
      
      <!-- Bootstrap -->
      <link href = "css/bootstrap.min.css" rel = "stylesheet">
      
      <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
      
      <!--[if lt IE 9]>
      <script src = "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src = "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
      <![endif]-->
      
   </head>
   
   <body>
    {% block welcome %}
    	{% include "users/heading.html" %}
    {% endblock %}
	<h3>This is our logo</h3>
		<div class="row">
		  	<div class="col-md-6">
		  		{% category_list_tag category_objs  %}
		  		
		    </div>
		    <div class="col-md-6">
		    	{% block body_content %}
		    	{% if request.user.is_authenticated %}

				<h3>Welcome {{ request.user.username }}</h3>
				<ul>
					<li><a href="{% url 'categories:add_category'%}">Add Category</li></a>
					<li><a href="{% url 'categories:show_category'%}">Show Categories</a></li>
					<li><a href="{% url 'categories:add_sub_category'%}">Add Sub Categories</a></li>
					<li><a href="{% url 'post:add_post'%}">Add Post</a></li>
					<li><a href="{% url 'post:view_post'%}">View All Post</a></li>
					<li><a href="{% url 'users:logout_view'%}">Logout</a></li>
				</ul>

				{% else %}
				<ul>
					<li><a href="{% url 'users:login_view'%}">Login</a></li>
					<li><a href="{% url 'users:register'%}">Registration</a></li>
				</ul>
				{% endif %}
				{% endblock %}
			</div>

		</div>		
   </body>
</html>






	

users/templates/users/login_view.html
{% extends 'users/index.html'%}
{% block body_content %}

<h1>Login</h1>
<form href="{% url 'users:login_view' %}" method='POST'>
	{% csrf_token %}
	<label for='username'>User Name</label>
	<input type="text" name="username"><br><br>
	<label for='password'>Password</label>
	<input type="password" name="password"><br><br>
	<input type="submit" name="submit">
</form>

{% endblock %}

users/templates/users/register.html
{% extends 'users/index.html'%}
{% block body_content %}


<h1>Registration</h1>
<form href="{% url 'users:register'%}" method="POST">
	{% csrf_token %}
	<label for="fname">First name:</label>
  	<input type="text" name="fname"><br><br>
  	<label for="lname">Last name:</label>
  	<input type="text" name="lname"><br><br>
  	<label for="username">User Name:</label>
  	<input type="text" name="username"><br><br>
  	<label for="password">Password:</label>
  	<input type="password" name="password"><br><br>
  	<label for="email">E-mail :</label>
  	<input type="text" name="email"><br><br>
  	<input type="submit" value="Submit">
</form>

{% endblock %}